version: '3'

services:
  test:
    build:
      context: ./
      dockerfile: tests/Dockerfile
    image: simple-twitter-bot-test:latest
    # volumes:
    #   - ./bots:/app
    #   - ./tests:/app/tests